language: ruby
rvm:
- 2.0
- 2.1
- 2.1
- 2.2
- ruby-head
bundler_args: "--jobs=2"
script: bundle exec rspec
branches:
  only:
  - master
notifications:
  email: false
  slack:
    secure: A2NfkamFIfgKSrV3KFMW+vYsCt9H9WgXJf6A4T+aAi8d/2WjeXbl0jB7FYBT8ut1Xgi43TrmoqDqvWSv9ly7yc0qFfIG4dtb8THmUJ+P11UDWPQXt40IFX/zX8ueQs9MA8h1sgtPyvenM7pRpKG+r6ooRHErPcYpx0zCb6JbDhY=
matrix:
  allow_failures:
  - rvm: ruby-head
